// Generated by tools/type_info/generate_type_info.py from the BLK_PROPERTY markers
// in the component headers. Don't edit it - the build regenerates it.

// clang-format off
GenerateEnum(
	EBreakableBehavior, "EBreakableBehavior",
	AddEnumField(PushFromImpactPoint, "PushFromImpactPoint")
	AddEnumField(UserVelocity, "UserVelocity")
)

GenerateEnum(
	EClothType, "EClothType",
	AddEnumField(CT_None, "None")
	AddEnumField(CT_Square, "Square")
)

GenerateEnum(
	ECollisionType, "ECollisionType",
	AddEnumField(CollisionType_Sphere, "Sphere")
	AddEnumField(CollisionType_Box, "Box")
	AddEnumField(CollisionType_StaticMesh, "StaticMesh")
	AddEnumField(CollisionType_CustomTriangles, "CustomTriangles")
)

GenerateEnum(
	ELevelType, "ELevelType",
	AddEnumField(LevelType_Menu, "Menu")
	AddEnumField(LevelType_2D, "2D")
)

GenerateEnum(
	eCinematicActionType, "eCinematicActionType",
	AddEnumField(CineAction_Override, "Override")
	AddEnumField(CineAction_Animate, "Animate")
	AddEnumField(CineAction_MoveTo, "MoveTo")
)

GenerateEnum(
	EBillboardType, "EBillboardType",
	AddEnumField(BT_FaceCamera, "FaceCamera")
	AddEnumField(BT_AxialBillboard, "AxialBillboard")
	AddEnumField(BT_AlignAlongVelocity, "AlignAlongVelocity")
)

GenerateEnum(
	eWidgetAnchor, "eWidgetAnchor",
	AddEnumField(TopLeft, "TopLeft")
	AddEnumField(MiddleLeft, "MiddleLeft")
	AddEnumField(BottomLeft, "BottomLeft")
	AddEnumField(TopCenter, "TopCenter")
	AddEnumField(MiddleCenter, "MiddleCenter")
	AddEnumField(BottomCenter, "BottomCenter")
	AddEnumField(TopRight, "TopRight")
	AddEnumField(MiddleRight, "MiddleRight")
	AddEnumField(BottomRight, "BottomRight")
)

GenerateEnum(
	eWidgetAxisLock, "eWidgetAxisLock",
	AddEnumField(LockAll, "LockAll")
	AddEnumField(LockXAxis, "LockXAxis")
	AddEnumField(LockYAxis, "LockYAxis")
)

GenerateEnum(
	ERenderPass, "ERenderPass",
	AddEnumField(RP_FirstPerson, "FirstPerson")
	AddEnumField(RP_Lighting, "Lighting")
	AddEnumField(RP_PreTranslucent, "PreTranslucent")
	AddEnumField(RP_Translucent, "Translucent")
	AddEnumField(RP_TranslucentWithDepth, "TranslucentWithDepth")
	AddEnumField(RP_PostLighting, "PostLighting")
	AddEnumField(RP_InWorldUI, "InWorldUI")
	AddEnumField(RP_Distortion, "Distortion")
	AddEnumField(RP_PostProcess, "PostProcess")
	AddEnumField(RP_UI, "UI")
	AddEnumField(RP_Debug, "Debug")
	AddEnumField(RP_MousePicker, "MousePicker")
)

GenerateEnum(
	ECullMode, "ECullMode",
	AddEnumField(CullMode_ShaderDefault, "ShaderDefault")
	AddEnumField(CullMode_None, "None")
	AddEnumField(CullMode_FrontFaces, "FrontFaces")
	AddEnumField(CullMode_BackFaces, "BackFaces")
)

GenerateEnum(
	EBlendMode, "EBlendMode",
	AddEnumField(None, "None")
	AddEnumField(Alpha, "Alpha")
	AddEnumField(Additive, "Additive")
)

GenerateClass(
	AnimationComponent,
	AddField("AnimationName", BLK_TYPEINFO_STRING, AnimationComponent, m_animation_name, false, "", String)
	AddField("Animation", BLK_TYPEINFO_ANIMATION, AnimationComponent, m_animation, false, "", Animation*)
	AddField("TimeScale", BLK_TYPEINFO_FLOAT, AnimationComponent, m_time_scale, false, "", f32)
	AddField("IsLooping", BLK_TYPEINFO_BOOL, AnimationComponent, m_is_looping, false, "", bool)
	AddField("AnimEvents", BLK_TYPEINFO_STRUCT, AnimationComponent, m_anim_events, true, "AnimEvent", std::vector<AnimEvent>)
)

GenerateClass(
	BreakableComponent,
	AddField("DestructibleType", BLK_TYPEINFO_ENUM, BreakableComponent, m_destructible_type, false, "EBreakableBehavior", EBreakableBehavior)
	AddField("LifeDuration", BLK_TYPEINFO_FLOAT, BreakableComponent, m_life_duration, false, "", f32)
	AddField("Gravity", BLK_TYPEINFO_VECTOR, BreakableComponent, m_gravity, false, "", Vec3)
	AddField("MinLinearVelocity", BLK_TYPEINFO_VECTOR, BreakableComponent, m_min_linear_velocity, false, "", Vec3)
	AddField("MaxLinearVelocity", BLK_TYPEINFO_VECTOR, BreakableComponent, m_max_linear_velocity, false, "", Vec3)
	AddField("MinAngularVelocity", BLK_TYPEINFO_FLOAT, BreakableComponent, m_min_angular_velocity, false, "", f32)
	AddField("MaxAngularVelocity", BLK_TYPEINFO_FLOAT, BreakableComponent, m_max_angular_velocity, false, "", f32)
	AddField("StartingHealth", BLK_TYPEINFO_FLOAT, BreakableComponent, m_starting_health, false, "", f32)
	AddField("CompleteDestructionFx", BLK_TYPEINFO_GAMEENTITY, BreakableComponent, m_complete_destruction_fx, false, "", GameEntityPtr)
	AddField("FxLocalOffset", BLK_TYPEINFO_VECTOR, BreakableComponent, m_fx_local_offset, false, "", Vec3)
	AddField("DebugResetSim", BLK_TYPEINFO_BOOL, BreakableComponent, m_bDebugResetSim, false, "", bool)
)

GenerateClass(
	ClothBone,
	AddField("BoneName", BLK_TYPEINFO_STRING, ClothBone, m_BoneName, false, "", String)
	AddField("NeighborBones", BLK_TYPEINFO_STRING, ClothBone, m_NeighborBones, true, "String", std::vector<String>)
	AddField("IsAnchored", BLK_TYPEINFO_BOOL, ClothBone, m_bIsAnchored, false, "", bool)
)

GenerateClass(
	ClothComponent,
	AddField("Width", BLK_TYPEINFO_INT, ClothComponent, m_Width, false, "", int)
	AddField("Height", BLK_TYPEINFO_INT, ClothComponent, m_Height, false, "", int)
	AddField("ClothType", BLK_TYPEINFO_ENUM, ClothComponent, m_ClothType, false, "EClothType", EClothType)
	AddField("BoneInfo", BLK_TYPEINFO_STRUCT, ClothComponent, m_BoneInfo, true, "ClothBone", std::vector<class ClothBone>)
	AddField("AdditionalBoneInfo", BLK_TYPEINFO_STRUCT, ClothComponent, m_AdditionalBoneInfo, true, "ClothBone", std::vector<class ClothBone>)
	AddField("CollisionSpheres", BLK_TYPEINFO_STRUCT, ClothComponent, m_CollisionSpheres, true, "BoneCollisionSphere", std::vector<class BoneCollisionSphere>)
	AddField("NumConstrainIterations", BLK_TYPEINFO_INT, ClothComponent, m_NumConstrainIterations, false, "", int)
	SetFieldMin("NumConstrainIterations", 1)
	AddField("Gravity", BLK_TYPEINFO_VECTOR, ClothComponent, m_gravity, false, "", Vec3)
	AddField("MaxWindVelocity", BLK_TYPEINFO_VECTOR, ClothComponent, m_MaxWindVelocity, false, "", Vec3)
	AddField("MinWindVelocity", BLK_TYPEINFO_VECTOR, ClothComponent, m_MinWindVelocity, false, "", Vec3)
	AddField("MaxWindGustDuration", BLK_TYPEINFO_FLOAT, ClothComponent, m_MaxWindGustDuration, false, "", float)
	AddField("MinWindGustDuration", BLK_TYPEINFO_FLOAT, ClothComponent, m_MinWindGustDuration, false, "", float)
	AddField("AddFakeOscillation", BLK_TYPEINFO_BOOL, ClothComponent, m_bAddFakeOscillation, false, "", bool)
)

GenerateClass(
	BoneCollisionSphere,
	AddField("BoneName", BLK_TYPEINFO_STRING, BoneCollisionSphere, m_BoneName, false, "", String)
	AddField("Sphere", BLK_TYPEINFO_VECTOR4, BoneCollisionSphere, m_Sphere, false, "", Vec4)
)

GenerateClass(
	CollisionComponent,
	AddField("CollisionType", BLK_TYPEINFO_ENUM, CollisionComponent, m_CollisionType, false, "ECollisionType", ECollisionType)
	AddField("Extent", BLK_TYPEINFO_VECTOR, CollisionComponent, m_Extent, false, "", Vec3)
	AddField("LocalSpaceCollisionSpheres", BLK_TYPEINFO_STRUCT, CollisionComponent, m_LocalSpaceCollisionSpheres, true, "BoneCollisionSphere", std::vector<BoneCollisionSphere>)
)

GenerateClass(
	Component,
	AddField("IsEnabled", BLK_TYPEINFO_BOOL, Component, m_IsEnabled, false, "", bool)
)

GenerateClass(
	GameComponent,
	AddField("StartingLifeTime", BLK_TYPEINFO_FLOAT, GameComponent, m_StartingLifeTime, false, "", float)
)

GenerateClass(
	TransformComponent,
	AddField("Name", BLK_TYPEINFO_STRING, TransformComponent, m_name, false, "", String)
	AddField("Position", BLK_TYPEINFO_VECTOR, TransformComponent, m_position, false, "", Vec3)
	AddField("Scale", BLK_TYPEINFO_VECTOR, TransformComponent, m_scale, false, "", Vec3)
	AddField("Rotation", BLK_TYPEINFO_VECTOR4, TransformComponent, m_rotation, false, "", Quat4)
)

GenerateClass(
	GameLogicComponent,
	AddField("DummyTemp", BLK_TYPEINFO_INT, GameLogicComponent, m_DummyTemp, false, "", int)
)

GenerateClass(
	DamageComponent,
	AddField("MinDamage", BLK_TYPEINFO_FLOAT, DamageComponent, m_MinDamage, false, "", float)
	AddField("MaxDamage", BLK_TYPEINFO_FLOAT, DamageComponent, m_MaxDamage, false, "", float)
)

GenerateClass(
	ActorComponent,
	AddField("MaxHealth", BLK_TYPEINFO_FLOAT, ActorComponent, m_MaxHealth, false, "", float)
)

GenerateClass(
	DeleteEntityComponent,
	AddField("Dummy", BLK_TYPEINFO_FLOAT, DeleteEntityComponent, m_Dummy, false, "", float)
)

GenerateClass(
	PlayerStartComponent,
	AddField("DummyVar", BLK_TYPEINFO_INT, PlayerStartComponent, m_DummyVar, false, "", int)
)

GenerateClass(
	AnimEvent,
	AddField("EventName", BLK_TYPEINFO_STRING, AnimEvent, m_EventName, false, "", String)
	AddField("EventValue", BLK_TYPEINFO_FLOAT, AnimEvent, m_EventValue, false, "", float)
	AddField("EventTime", BLK_TYPEINFO_FLOAT, AnimEvent, m_EventTime, false, "", float)
)

GenerateClass(
	VectorAnimEvent,
	AddField("EventName", BLK_TYPEINFO_STRING, VectorAnimEvent, m_EventName, false, "", String)
	AddField("EventValue", BLK_TYPEINFO_VECTOR4, VectorAnimEvent, m_EventValue, false, "", Vec4)
	AddField("EventTime", BLK_TYPEINFO_FLOAT, VectorAnimEvent, m_EventTime, false, "", float)
)

GenerateClass(
	EditorGlobalSettingsComponent,
	AddField("CameraSpeedIdx", BLK_TYPEINFO_INT, EditorGlobalSettingsComponent, m_CameraSpeedIdx, false, "", int)
)

GenerateClass(
	EditorLevelSettingsComponent,
	AddField("CameraPosition", BLK_TYPEINFO_VECTOR, EditorLevelSettingsComponent, m_CameraPosition, false, "", Vec3)
	AddField("CameraRotation", BLK_TYPEINFO_VECTOR4, EditorLevelSettingsComponent, m_CameraRotation, false, "", Quat4)
)

GenerateClass(
	DebugSphereCollision,
	AddField("CollisionModel", BLK_TYPEINFO_STATICMODEL, DebugSphereCollision, m_pCollisionModel, false, "", Model*)
)

GenerateClass(
	GaussianSplatComponent,
	AddField("Model", BLK_TYPEINFO_STATICMODEL, GaussianSplatComponent, m_model, false, "", const Model*)
	AddField("SplatFalloff", BLK_TYPEINFO_FLOAT, GaussianSplatComponent, m_splat_falloff, false, "", f32)
	AddField("SplatScale", BLK_TYPEINFO_FLOAT, GaussianSplatComponent, m_splat_scale, false, "", f32)
	AddField("Contrast", BLK_TYPEINFO_FLOAT, GaussianSplatComponent, m_contrast, false, "", f32)
	AddField("MaxShDegree", BLK_TYPEINFO_INT, GaussianSplatComponent, m_max_sh_degree, false, "", i32)
	AddField("GpuSort", BLK_TYPEINFO_BOOL, GaussianSplatComponent, m_gpu_sort, false, "", bool)
)

GenerateClass(
	LevelComponent,
	AddField("LevelType", BLK_TYPEINFO_ENUM, LevelComponent, m_LevelType, false, "ELevelType", ELevelType)
	AddField("GlobalModelScale", BLK_TYPEINFO_FLOAT, LevelComponent, m_GlobalModelScale, false, "", f32)
	AddField("EditorIconScale", BLK_TYPEINFO_FLOAT, LevelComponent, m_EditorIconScale, false, "", f32)
	AddField("GlobalVolumeScale", BLK_TYPEINFO_FLOAT, LevelComponent, m_GlobalVolumeScale, false, "", f32)
)

GenerateClass(
	CinematicAction,
	AddField("CineActionType", BLK_TYPEINFO_ENUM, CinematicAction, m_CineActionType, false, "eCinematicActionType", eCinematicActionType)
	AddField("StringParam", BLK_TYPEINFO_STRING, CinematicAction, m_StringParam, false, "", String)
	AddField("FloatParam", BLK_TYPEINFO_FLOAT, CinematicAction, m_FloatParam, false, "", f32)
	AddField("EntityParam", BLK_TYPEINFO_GAMEENTITY, CinematicAction, m_EntityParam, false, "", GameEntityPtr)
	AddField("VectorParam", BLK_TYPEINFO_VECTOR, CinematicAction, m_VectorParam, false, "", Vec3)
	AddField("ActionStartTime", BLK_TYPEINFO_FLOAT, CinematicAction, m_ActionStartTime, false, "", f32)
	AddField("ActionDuration", BLK_TYPEINFO_FLOAT, CinematicAction, m_ActionDuration, false, "", f32)
)

GenerateClass(
	CinematicComponent,
	AddField("Actions", BLK_TYPEINFO_STRUCT, CinematicComponent, m_Actions, true, "CinematicAction", std::vector<CinematicAction>)
)

GenerateClass(
	LightComponent,
	AddField("Materials", BLK_TYPEINFO_STRUCT, LightComponent, m_materials, true, "MaterialComponent", std::vector<MaterialComponent>)
	AddField("Color", BLK_TYPEINFO_VECTOR4, LightComponent, m_color, false, "", Color)
	AddField("CastsShadow", BLK_TYPEINFO_BOOL, LightComponent, m_casts_shadow, false, "", bool)
)

GenerateClass(
	PointLightComponent,
	AddField("Radius", BLK_TYPEINFO_FLOAT, PointLightComponent, m_radius, false, "", f32)
)

GenerateClass(
	CylindricalLightComponent,
	AddField("Length", BLK_TYPEINFO_FLOAT, CylindricalLightComponent, m_length, false, "", f32)
)

GenerateClass(
	DirectionalLightComponent,
	AddField("CascadeStartDistances", BLK_TYPEINFO_FLOAT, DirectionalLightComponent, m_cascade_start_distances, true, "float", std::vector<f32>)
)

GenerateClass(
	LightShaftsComponent,
	AddField("Texture", BLK_TYPEINFO_TEXTURE, LightShaftsComponent, m_Texture, false, "", Texture*)
	AddField("Color", BLK_TYPEINFO_VECTOR4, LightShaftsComponent, m_Color, false, "", Color)
	AddField("BaseWidth", BLK_TYPEINFO_FLOAT, LightShaftsComponent, m_BaseWidth, false, "", f32)
	AddField("BaseHeight", BLK_TYPEINFO_FLOAT, LightShaftsComponent, m_BaseHeight, false, "", f32)
	AddField("IterationWidth", BLK_TYPEINFO_FLOAT, LightShaftsComponent, m_IterationWidth, false, "", f32)
	AddField("IterationHeight", BLK_TYPEINFO_FLOAT, LightShaftsComponent, m_IterationHeight, false, "", f32)
	AddField("NumIterations", BLK_TYPEINFO_INT, LightShaftsComponent, m_NumIterations, false, "", i32)
	AddField("Directional", BLK_TYPEINFO_BOOL, LightShaftsComponent, m_Directional, false, "", bool)
)

GenerateClass(
	FogComponent,
	AddField("Color", BLK_TYPEINFO_VECTOR4, FogComponent, m_Color, false, "", Color)
	AddField("StartDistance", BLK_TYPEINFO_FLOAT, FogComponent, m_StartDistance, false, "", f32)
	AddField("EndDistance", BLK_TYPEINFO_FLOAT, FogComponent, m_EndDistance, false, "", f32)
)

GenerateClass(
	StaticModelComponent,
	AddField("Model", BLK_TYPEINFO_STATICMODEL, StaticModelComponent, m_model, false, "", const Model*)
)

GenerateClass(
	AnimComponent,
	AddField("AnimationName", BLK_TYPEINFO_STRING, AnimComponent, m_animation_name, false, "", String)
	AddField("Animation", BLK_TYPEINFO_ANIMATION, AnimComponent, m_animation, false, "", Animation*)
	AddField("TimeScale", BLK_TYPEINFO_FLOAT, AnimComponent, m_time_scale, false, "", float)
	AddField("IsLooping", BLK_TYPEINFO_BOOL, AnimComponent, m_is_looping, false, "", bool)
	AddField("AnimEvents", BLK_TYPEINFO_STRUCT, AnimComponent, m_anim_events, true, "AnimEvent", std::vector<AnimEvent>)
)

GenerateClass(
	SkeletalModelComponent,
	AddField("Model", BLK_TYPEINFO_STATICMODEL, SkeletalModelComponent, m_model, false, "", class Model*)
	AddField("Animations", BLK_TYPEINFO_STRUCT, SkeletalModelComponent, m_Animations, true, "AnimComponent", std::vector<AnimComponent>)
	AddField("DebugAnimIndex", BLK_TYPEINFO_INT, SkeletalModelComponent, m_DebugAnimIndex, false, "", i32)
)

GenerateClass(
	FlingPhysicsComponent,
	AddField("MinLinearVelocity", BLK_TYPEINFO_VECTOR, FlingPhysicsComponent, m_min_linear_velocity, false, "", Vec3)
	AddField("MaxLinearVelocity", BLK_TYPEINFO_VECTOR, FlingPhysicsComponent, m_max_linear_velocity, false, "", Vec3)
	AddField("MinAngularSpeed", BLK_TYPEINFO_FLOAT, FlingPhysicsComponent, m_MinAngularSpeed, false, "", float)
	AddField("MaxAngularSpeed", BLK_TYPEINFO_FLOAT, FlingPhysicsComponent, m_MaxAngularSpeed, false, "", float)
	AddField("Gravity", BLK_TYPEINFO_VECTOR, FlingPhysicsComponent, m_gravity, false, "", Vec3)
)

GenerateClass(
	ModelEmitter,
	AddField("Model", BLK_TYPEINFO_STATICMODEL, ModelEmitter, m_model, false, "", Model*)
	AddField("Materials", BLK_TYPEINFO_STRUCT, ModelEmitter, m_materials, true, "MaterialComponent", std::vector<MaterialComponent>)
)

GenerateClass(
	ParticleComponent,
	AddField("MaterialList", BLK_TYPEINFO_STRUCT, ParticleComponent, m_materials, true, "MaterialComponent", std::vector<MaterialComponent>)
	AddField("TotalDuration", BLK_TYPEINFO_FLOAT, ParticleComponent, m_total_duration, false, "", f32)
	AddField("MaxParticlesToEmit", BLK_TYPEINFO_INT, ParticleComponent, m_max_particles_to_emit, false, "", i32)
	AddField("StartDelay", BLK_TYPEINFO_FLOAT, ParticleComponent, m_start_delay, false, "", f32)
	AddField("MinSpawnRate", BLK_TYPEINFO_FLOAT, ParticleComponent, m_min_spawn_rate, false, "", f32)
	SetFieldMin("MinSpawnRate", 0)
	AddField("MaxSpawnRate", BLK_TYPEINFO_FLOAT, ParticleComponent, m_max_spawn_rate, false, "", f32)
	SetFieldMin("MaxSpawnRate", 0)
	AddField("MinStartVelocity", BLK_TYPEINFO_VECTOR, ParticleComponent, m_min_start_velocity, false, "", Vec3)
	AddField("MaxStartVelocity", BLK_TYPEINFO_VECTOR, ParticleComponent, m_max_start_velocity, false, "", Vec3)
	AddField("VelocityOverLifeCurve", BLK_TYPEINFO_STRUCT, ParticleComponent, m_velocity_over_life_curve, true, "AnimEvent", std::vector<AnimEvent>)
	AddField("MinEndVelocity", BLK_TYPEINFO_VECTOR, ParticleComponent, m_min_end_velocity, false, "", Vec3)
	AddField("MaxEndVelocity", BLK_TYPEINFO_VECTOR, ParticleComponent, m_max_end_velocity, false, "", Vec3)
	AddField("MinStartRotationRate", BLK_TYPEINFO_FLOAT, ParticleComponent, m_min_start_rotation_rate, false, "", f32)
	AddField("MaxStartRotationRate", BLK_TYPEINFO_FLOAT, ParticleComponent, m_max_start_rotation_rate, false, "", f32)
	AddField("MinEndRotationRate", BLK_TYPEINFO_FLOAT, ParticleComponent, m_min_end_rotation_rate, false, "", f32)
	AddField("MaxEndRotationRate", BLK_TYPEINFO_FLOAT, ParticleComponent, m_max_end_rotation_rate, false, "", f32)
	AddField("MinStart3DRotation", BLK_TYPEINFO_VECTOR4, ParticleComponent, m_min_start_3d_rotation, false, "", Vec4)
	AddField("MaxStart3DRotation", BLK_TYPEINFO_VECTOR4, ParticleComponent, m_max_start_3d_rotation, false, "", Vec4)
	AddField("MinStart3DOffset", BLK_TYPEINFO_VECTOR, ParticleComponent, m_min_start_3d_offset, false, "", Vec3)
	AddField("MaxStart3DOffset", BLK_TYPEINFO_VECTOR, ParticleComponent, m_max_start_3d_offset, false, "", Vec3)
	AddField("MinStartSize", BLK_TYPEINFO_VECTOR, ParticleComponent, m_min_start_size, false, "", Vec3)
	AddField("MaxStartSize", BLK_TYPEINFO_VECTOR, ParticleComponent, m_max_start_size, false, "", Vec3)
	AddField("MinEndSize", BLK_TYPEINFO_VECTOR, ParticleComponent, m_min_end_size, false, "", Vec3)
	AddField("MaxEndSize", BLK_TYPEINFO_VECTOR, ParticleComponent, m_max_end_size, false, "", Vec3)
	AddField("MinDuration", BLK_TYPEINFO_FLOAT, ParticleComponent, m_min_duration, false, "", f32)
	AddField("MaxDuration", BLK_TYPEINFO_FLOAT, ParticleComponent, m_max_duration, false, "", f32)
	AddField("StartColor", BLK_TYPEINFO_VECTOR4, ParticleComponent, m_start_color, false, "", Vec4)
	AddField("EndColor", BLK_TYPEINFO_VECTOR4, ParticleComponent, m_end_color, false, "", Vec4)
	AddField("SizeOverLifeCurve", BLK_TYPEINFO_STRUCT, ParticleComponent, m_size_over_life_curve, true, "VectorAnimEvent", std::vector<VectorAnimEvent>)
	AddField("RotationOverLifeCurve", BLK_TYPEINFO_STRUCT, ParticleComponent, m_rotation_over_life_curve, true, "VectorAnimEvent", std::vector<VectorAnimEvent>)
	AddField("ColorOverLifeCurve", BLK_TYPEINFO_STRUCT, ParticleComponent, m_color_over_life_curve, true, "VectorAnimEvent", std::vector<VectorAnimEvent>)
	AddField("AlphaOverLifeCurve", BLK_TYPEINFO_STRUCT, ParticleComponent, m_alpha_over_life_curve, true, "AnimEvent", std::vector<AnimEvent>)
	AddField("Gravity", BLK_TYPEINFO_VECTOR, ParticleComponent, m_gravity, false, "", Vec3)
	AddField("MinBurstCount", BLK_TYPEINFO_INT, ParticleComponent, m_min_burst_count, false, "", i32)
	AddField("MaxBurstCount", BLK_TYPEINFO_INT, ParticleComponent, m_max_burst_count, false, "", i32)
	AddField("BillboardType", BLK_TYPEINFO_ENUM, ParticleComponent, m_billboard_type, false, "EBillboardType", EBillboardType)
	AddField("ModelEmitter", BLK_TYPEINFO_STRUCT, ParticleComponent, m_model_emitter, true, "StaticModelComponent", std::vector<StaticModelComponent>)
	AddField("DebugPlayEntity", BLK_TYPEINFO_BOOL, ParticleComponent, m_debug_play_entity, false, "", bool)
)

GenerateClass(
	ShaderParamComponent,
	AddField("ParamName", BLK_TYPEINFO_STRING, ShaderParamComponent, m_param_name, false, "", String)
	AddField("Texture", BLK_TYPEINFO_TEXTURE, ShaderParamComponent, m_texture, false, "", Texture*)
	AddField("Vector", BLK_TYPEINFO_VECTOR4, ShaderParamComponent, m_vector, false, "", Vec4)
)

GenerateClass(
	ShaderModifierComponent,
	AddField("ShaderVectorEvents", BLK_TYPEINFO_STRUCT, ShaderModifierComponent, m_ShaderVectorEvents, true, "VectorAnimEvent", std::vector<VectorAnimEvent>)
)

GenerateClass(
	MaterialComponent,
	AddField("Shader", BLK_TYPEINFO_SHADER, MaterialComponent, m_shader, false, "", Shader*)
	AddField("CullModeOverride", BLK_TYPEINFO_ENUM, MaterialComponent, m_cull_mode_override, false, "ECullMode", ECullMode)
	AddField("BlendOverride", BLK_TYPEINFO_ENUM, MaterialComponent, m_blend_override, false, "EBlendMode", EBlendMode)
	AddField("ShaderParams", BLK_TYPEINFO_STRUCT, MaterialComponent, m_shader_params, true, "ShaderParamComponent", std::vector<ShaderParamComponent>)
)

GenerateClass(
	RenderComponent,
	AddField("RenderPass", BLK_TYPEINFO_ENUM, RenderComponent, m_render_pass, false, "ERenderPass", ERenderPass)
	AddField("RenderOrderBias", BLK_TYPEINFO_FLOAT, RenderComponent, m_render_order_bias, false, "", float)
	AddField("Materials", BLK_TYPEINFO_STRUCT, RenderComponent, m_materials, true, "MaterialComponent", std::vector<MaterialComponent>)
	AddField("CastsShadow", BLK_TYPEINFO_BOOL, RenderComponent, m_casts_shadow, false, "", bool)
)

GenerateClass(
	Grass,
	AddField("GrassShader", BLK_TYPEINFO_SHADER, Grass, m_pGrassShader, false, "", Shader*)
	AddField("GrassCellsPerTerrainSide", BLK_TYPEINFO_INT, Grass, m_grassCellsPerTerrainSide, false, "", int)
	SetFieldMin("GrassCellsPerTerrainSide", 1)
	AddField("ShaderParams", BLK_TYPEINFO_STRUCT, Grass, m_ShaderParams, true, "ShaderParamComponent", std::vector<ShaderParamComponent>)
	AddField("PatchStartCullDistance", BLK_TYPEINFO_FLOAT, Grass, m_PatchStartCullDistance, false, "", f32)
	AddField("PatchEndCullDistance", BLK_TYPEINFO_FLOAT, Grass, m_PatchEndCullDistance, false, "", f32)
	AddField("PatchesPerCellSide", BLK_TYPEINFO_INT, Grass, m_PatchesPerCellSide, false, "", i32)
	AddField("BladeMinWidth", BLK_TYPEINFO_FLOAT, Grass, m_BladeMinWidth, false, "", f32)
	AddField("BladeMaxWidth", BLK_TYPEINFO_FLOAT, Grass, m_BladeMaxWidth, false, "", f32)
	AddField("BladeMinHeight", BLK_TYPEINFO_FLOAT, Grass, m_BladeMinHeight, false, "", f32)
	AddField("BladeMaxHeight", BLK_TYPEINFO_FLOAT, Grass, m_BladeMaxHeight, false, "", f32)
	AddField("MaxPatchJitterOffset", BLK_TYPEINFO_FLOAT, Grass, m_MaxPatchJitterOffset, false, "", f32)
	AddField("MaxBladeJitterOffset", BLK_TYPEINFO_FLOAT, Grass, m_MaxBladeJitterOffset, false, "", f32)
	AddField("FakeAODarkness", BLK_TYPEINFO_FLOAT, Grass, m_FakeAODarkness, false, "", f32)
	AddField("FakeAOPower", BLK_TYPEINFO_FLOAT, Grass, m_FakeAOPower, false, "", f32)
	AddField("FakeAOClipPlaneFadeStartDist", BLK_TYPEINFO_FLOAT, Grass, m_FakeAOClipPlaneFadeStartDist, false, "", f32)
)

GenerateClass(
	GrassZone,
	AddField("Center", BLK_TYPEINFO_VECTOR, GrassZone, m_Center, false, "", Vec3)
	AddField("Extents", BLK_TYPEINFO_VECTOR, GrassZone, m_Extents, false, "", Vec3)
)

GenerateClass(
	TerrainComponent,
	AddField("HeightMap", BLK_TYPEINFO_TEXTURE, TerrainComponent, m_height_map, false, "", Texture*)
	AddField("HeightScale", BLK_TYPEINFO_FLOAT, TerrainComponent, m_height_scale, false, "", f32)
	AddField("WorldWidth", BLK_TYPEINFO_FLOAT, TerrainComponent, m_world_width, false, "", f32)
	AddField("VertexDimensions", BLK_TYPEINFO_INT, TerrainComponent, m_vertex_dimensions, false, "", i32)
	AddField("TerrainSmoothFilterWidth", BLK_TYPEINFO_INT, TerrainComponent, m_terrain_smooth_filter_width, false, "", i32)
	AddField("SplatMap", BLK_TYPEINFO_TEXTURE, TerrainComponent, m_splat_map, false, "", Texture*)
	AddField("Grass", BLK_TYPEINFO_STRUCT, TerrainComponent, m_grass, true, "Grass", std::vector<Grass>)
	AddField("GrassZones", BLK_TYPEINFO_STRUCT, TerrainComponent, m_grass_zones, true, "GrassZone", std::vector<GrassZone>)
	AddField("DebugForceGenTerrain", BLK_TYPEINFO_BOOL, TerrainComponent, m_debug_force_gen_terrain, false, "", bool)
)

GenerateClass(
	UIComponent,
	AddField("AuthoredWidth", BLK_TYPEINFO_INT, UIComponent, m_AuthoredWidth, false, "", int)
	AddField("AuthoredHeight", BLK_TYPEINFO_INT, UIComponent, m_AuthoredHeight, false, "", int)
	AddField("NormalizedAnchorPoint", BLK_TYPEINFO_VECTOR, UIComponent, m_NormalizedAnchorPoint, false, "", Vec3)
	AddField("UIToScreenSizeRatio", BLK_TYPEINFO_VECTOR, UIComponent, m_UIToScreenSizeRatio, false, "", Vec3)
)

GenerateClass(
	UIWidgetComponent,
	AddField("Materials", BLK_TYPEINFO_STRUCT, UIWidgetComponent, m_Materials, true, "MaterialComponent", std::vector<MaterialComponent>)
	AddField("ChildWidgets", BLK_TYPEINFO_STRUCT, UIWidgetComponent, m_ChildWidgets, true, "UIWidgetComponent", std::vector<UIWidgetComponent>)
	AddField("StartingPosition", BLK_TYPEINFO_VECTOR, UIWidgetComponent, m_StartingPosition, false, "", Vec3)
	AddField("StartingSize", BLK_TYPEINFO_VECTOR, UIWidgetComponent, m_StartingSize, false, "", Vec3)
	AddField("Anchor", BLK_TYPEINFO_ENUM, UIWidgetComponent, m_Anchor, false, "eWidgetAnchor", UIWidgetComponent::eWidgetAnchor)
	AddField("AxisLock", BLK_TYPEINFO_ENUM, UIWidgetComponent, m_AxisLock, false, "eWidgetAxisLock", UIWidgetComponent::eWidgetAxisLock)
)

GenerateClass(
	UISlider,
	AddField("SliderBoundsMin", BLK_TYPEINFO_VECTOR, UISlider, m_SliderBoundsMin, false, "", Vec3)
	AddField("SliderBoundsMax", BLK_TYPEINFO_VECTOR, UISlider, m_SliderBoundsMax, false, "", Vec3)
)

GenerateClass(
	SoundData,
	AddField("WaveFile", BLK_TYPEINFO_SOUNDWAVE, SoundData, m_pWaveFile, false, "", class WaveFile*)
	AddField("Radius", BLK_TYPEINFO_FLOAT, SoundData, m_Radius, false, "", float)
	AddField("Volume", BLK_TYPEINFO_FLOAT, SoundData, m_Volume, false, "", float)
	AddField("Looping", BLK_TYPEINFO_BOOL, SoundData, m_bLooping, false, "", bool)
	AddField("DebugPlaySound", BLK_TYPEINFO_BOOL, SoundData, m_bDebugPlaySound, false, "", bool)
)

GenerateClass(
	PlaySoundComponent,
	AddField("MinStartDelay", BLK_TYPEINFO_FLOAT, PlaySoundComponent, m_MinStartDelay, false, "", float)
	AddField("MaxStartDelay", BLK_TYPEINFO_FLOAT, PlaySoundComponent, m_MaxStartDelay, false, "", float)
	AddField("SoundData", BLK_TYPEINFO_STRUCT, PlaySoundComponent, m_SoundData, true, "SoundData", std::vector<SoundData>)
)
