"""Generates the reflection tables from BLK_PROPERTY markers in component headers.

    python tools/type_info/generate_type_info.py            # every project
    python tools/type_info/generate_type_info.py engine     # one project
    python tools/type_info/generate_type_info.py --check    # exit 1 if an output is stale

blk_engine.vcxproj and blaise.vcxproj run it as a pre-build step. See README.md.
"""

import argparse
import os
import re
import sys
from dataclasses import dataclass, field

REPO = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

# "scan" headers are generated for; "context" headers only resolve types (blaise
# components use engine enums and components).
PROJECTS = {
	"engine": {
		"scan": ["blk_engine"],
		"context": [],
		"tables": "blk_engine/game/type_info_generated.h",
		"instances": "blk_engine/game/type_info_generated.inl",
	},
	"blaise": {
		"scan": ["blaise/src"],
		"context": ["blk_engine"],
		"tables": "blaise/src/game/blaise_gen.h",
		"instances": "blaise/src/game/blaise_gen.inl",
	},
}

# Vendored, generated and build-output directories. Nothing reflected lives in them.
SKIP_DIRS = {".git", "External", "SDL3", "dx12", "dxtk", "generated", "lib", "x64"}

# Member type -> BLK_TYPEINFO_* tag. Keys are normalized: const and the
# class/struct/enum keywords dropped, std:: spelled out, no spaces.
SCALAR_TAGS = {
	"bool": "BOOL",
	"int": "INT",
	"i32": "INT",
	"float": "FLOAT",
	"f32": "FLOAT",
	"String": "STRING",
	"std::string": "STD_STRING",
	"Vec3": "VECTOR",
	"Vec4": "VECTOR4",
	"Quat4": "VECTOR4",
	"Color": "VECTOR4",  # Color derives from Vec4
	"Texture*": "TEXTURE",
	"Shader*": "SHADER",
	"Model*": "STATICMODEL",
	"Animation*": "ANIMATION",
	"WaveFile*": "SOUNDWAVE",
	"GameEntityPtr": "GAMEENTITY",
}

# std::vector element types whose vector operations NameToTypeInfoMap's
# constructor registers, and the key they're registered under. Component element
# types register their own, keyed by class name.
PRIMITIVE_ARRAY_KEYS = {"float": "float", "f32": "float", "String": "String", "Vec4": "Vec4"}

HEADER = """\
// Generated by tools/type_info/generate_type_info.py from the BLK_PROPERTY markers
// in the component headers. Don't edit it - the build regenerates it.
"""


class Diagnostics:
	"""Collects messages in the format MSBuild picks up as build errors/warnings."""

	def __init__(self):
		self.errors = []
		self.warnings = []

	def error(self, path, line, msg):
		self.errors.append(f"{path}({line}): error TYPEINFO: {msg}")

	def warning(self, path, line, msg):
		self.warnings.append(f"{path}({line}): warning TYPEINFO: {msg}")


# ---------------------------------------------------------------------------
# Tokenizer

TOKEN_RE = re.compile(
	r"""
	(?P<nl>\n)
	|(?P<ws>[ \t\r\f\v]+)
	|(?P<comment>//[^\n]*|/\*.*?\*/)
	|(?P<string>"(?:\\.|[^"\\\n])*")
	|(?P<char>'(?:\\.|[^'\\\n])*')
	|(?P<ident>[A-Za-z_]\w*)
	|(?P<number>\.?\d(?:[eEpP][+-]|[\w.'])*)
	|(?P<punct>::|->|[^\s\w])
	|(?P<other>.)
	""",
	re.S | re.X,
)


@dataclass(slots=True)
class Token:
	kind: str  # ident, number, string, char, punct, other, pp
	text: str
	pos: int
	line: int


def tokenize(text):
	tokens = []
	pos, line, line_start = 0, 1, True
	n = len(text)
	while pos < n:
		m = TOKEN_RE.match(text, pos)
		kind, s = m.lastgroup, m.group()
		if kind == "nl":
			line += 1
			line_start = True
		elif kind == "ws":
			pass
		elif kind == "comment":
			line += s.count("\n")
		elif s == "#" and line_start:
			# A preprocessor directive, backslash continuations included.
			start_line, end = line, pos
			while True:
				nl = text.find("\n", end)
				if nl == -1:
					end = n
					break
				if text[end:nl].rstrip("\r").endswith("\\"):
					end = nl + 1
					line += 1
					continue
				end = nl
				break
			tokens.append(Token("pp", text[pos:end], pos, start_line))
			pos = end
			continue
		else:
			line_start = False
			tokens.append(Token(kind, s, pos, line))
		pos = m.end()
	return drop_disabled(tokens)


def drop_disabled(tokens):
	"""Removes code inside #if 0 blocks."""
	out, skip = [], 0
	for t in tokens:
		directive = t.text[1:].split() if t.kind == "pp" else []
		word = directive[0] if directive else ""
		if skip:
			if word in ("if", "ifdef", "ifndef"):
				skip += 1
			elif word == "endif" or (word in ("else", "elif") and skip == 1):
				skip -= 1
			continue
		if word == "if" and directive[1:2] == ["0"]:
			skip = 1
			continue
		out.append(t)
	return out


# ---------------------------------------------------------------------------
# Header parser

@dataclass
class Property:
	member: str
	type_tokens: list
	saved_name: str | None  # from BLK_PROPERTY(SerializedAs = ...)
	line: int
	specs: dict = field(default_factory=dict)


@dataclass
class Component:
	name: str
	parent: str
	qualname: str
	path: str
	line: int
	props: list = field(default_factory=list)


@dataclass
class Enumerator:
	ident: str
	saved_name: str | None  # from BLK_ENUM(SerializedAs = ...)
	skip: bool
	line: int
	end: int  # offset just past the identifier


@dataclass
class Enum:
	name: str
	qualname: str
	path: str
	line: int
	enumerators: list
	problem: str | None


@dataclass
class Member:
	cls: str  # qualified name of the enclosing class
	name: str
	type_tokens: list
	problem: str | None
	path: str
	line: int
	pos: int  # offset of the declaration's first token


@dataclass
class Frame:
	kind: str  # file, namespace, class, block
	qualname: str = ""
	name: str | None = None
	stmt: list = field(default_factory=list)
	skip_stmt: bool = False
	marker: tuple | None = None  # (saved_name, token) of a pending BLK_PROPERTY
	component: Component | None = None
	props: list = field(default_factory=list)
	closes_stmt: bool = False  # a function body: closing it ends the enclosing statement


def scoped(outer, name):
	return f"{outer}::{name}" if outer else name


def unquote(token):
	return token.text[1:-1]


# Specifier -> (value kind, wired up yet). Anything else in a marker is a build error,
# and so is a specifier that parses but nothing acts on, so a hint can't silently do
# nothing. Flip the flag in the same change that makes one take effect.
PROPERTY_SPECIFIERS = {
	"SerializedAs": ("string", True),
	"MinVal": ("number", True),
	"MaxVal": ("number", True),
}
ENUM_SPECIFIERS = {
	"SerializedAs": ("string", True),
	"Skip": ("flag", True),
}


def parse_specifiers(tokens, table, marker, report):
	"""Reads a marker's Key = value list. Returns {name: value}; flags map to True."""
	specs = {}
	i = 0
	while i < len(tokens):
		name = tokens[i]
		if name.kind != "ident" or name.text not in table:
			report(marker.line, f"{marker.text}: unknown specifier '{name.text}'; expected one of {', '.join(table)}")
			return specs
		kind, implemented = table[name.text]
		if not implemented:
			report(marker.line, f"{marker.text}: {name.text} isn't wired up yet, so it would have no effect")
			return specs
		i += 1
		value = True
		if i < len(tokens) and tokens[i].text == "=":
			i += 1
			if kind == "flag":
				report(marker.line, f"{marker.text}: {name.text} takes no value")
				return specs
			negate = i < len(tokens) and tokens[i].text == "-"
			i += negate
			token = tokens[i] if i < len(tokens) else None
			if kind == "string" and (token is None or token.kind != "string"):
				report(marker.line, f'{marker.text}: {name.text} takes a string, as {name.text} = "Something"')
				return specs
			if kind == "number" and (token is None or token.kind != "number"):
				report(marker.line, f"{marker.text}: {name.text} takes a number")
				return specs
			value = unquote(token) if kind == "string" else float(token.text) * (-1 if negate else 1)
			i += 1
		elif kind != "flag":
			report(marker.line, f"{marker.text}: {name.text} needs a value, as {name.text} = ...")
			return specs
		specs[name.text] = value
		if i < len(tokens):
			if tokens[i].text != ",":
				report(marker.line, f"{marker.text}: expected ',' between specifiers, found '{tokens[i].text}'")
				return specs
			i += 1
	return specs


class HeaderParser:
	"""Finds components, BLK_PROPERTY members, enums and data members in one header.

	Not a C++ parser: it tracks class/namespace/function scopes and splits class
	bodies into statements, which is enough for member declarations. Anything it
	gets wrong about a property's type is caught by the static_assert AddField
	emits.
	"""

	def __init__(self, path, text, diag):
		self.path = path
		self.toks = tokenize(text)
		self.diag = diag
		self.components = []
		self.enums = []
		self.members = []

	def text(self, i):
		return self.toks[i].text if i < len(self.toks) else ""

	def error(self, line, msg):
		self.diag.error(self.path, line, msg)

	def match(self, i):
		"""Index of the bracket that closes the one at i."""
		open_ = self.toks[i].text
		close = {"(": ")", "{": "}", "[": "]"}[open_]
		depth = 0
		for j in range(i, len(self.toks)):
			t = self.toks[j]
			if t.kind != "punct":
				continue
			if t.text == open_:
				depth += 1
			elif t.text == close:
				depth -= 1
				if depth == 0:
					return j
		return len(self.toks) - 1

	def parse(self):
		toks = self.toks
		stack = [Frame("file")]
		i = 0
		while i < len(toks):
			t = toks[i]
			top = stack[-1]
			if t.kind == "pp":
				i += 1
				continue
			if top.kind == "block":
				if t.kind == "punct" and t.text == "{":
					stack.append(Frame("block"))
				elif t.kind == "punct" and t.text == "}":
					stack.pop()
					if top.closes_stmt:
						self.reset(stack[-1])
				i += 1
				continue

			if t.kind == "ident":
				nxt = self.text(i + 1)
				if t.text == "BLK_DECLARE_COMPONENT" and nxt == "(":
					i = self.declare_component(i, top)
					continue
				if t.text in ("public", "protected", "private") and nxt == ":":
					self.reset(top)
					i += 2
					continue
				if t.text == "BLK_PROPERTY" and not top.stmt:
					i = self.property_marker(i, top)
					continue
				if t.text == "BLK_ENUM":
					self.error(t.line, "BLK_ENUM marks an enumerator; it can't be used here")
				if t.text == "namespace" and not top.stmt:
					j = i + 1
					while toks[j].kind == "ident" or toks[j].text == "::":
						j += 1
					if toks[j].text == "{":
						name = "".join(x.text for x in toks[i + 1:j])
						stack.append(Frame("namespace", qualname=scoped(top.qualname, name)))
						i = j + 1
						continue
				if t.text in ("class", "struct", "union"):
					head = self.class_head(i)
					if head:
						brace, name = head
						if top.marker:
							self.error(top.marker[1].line, "BLK_PROPERTY must be followed by a data member declaration")
							top.marker = None
						qualname = scoped(top.qualname, name or "<anonymous>")
						stack.append(Frame("class", qualname=qualname, name=name))
						i = brace + 1
						continue
				if t.text == "enum":
					end = self.enum_definition(i, top)
					if end is not None:
						i = end
						continue
			elif t.kind == "punct":
				if t.text == "{":
					if self.is_function_body(top.stmt):
						if top.marker:
							self.error(top.marker[1].line, "BLK_PROPERTY must be followed by a data member declaration")
							top.marker = None
						stack.append(Frame("block", closes_stmt=True))
						i += 1
						continue
					# A brace initializer: part of the statement.
					j = self.match(i)
					top.stmt.extend(toks[i:j + 1])
					i = j + 1
					continue
				if t.text == "}":
					if top.kind in ("class", "namespace"):
						stack.pop()
						if top.kind == "class":
							self.close_class(top)
							# The class definition was the statement; what follows is at most declarators.
							stack[-1].skip_stmt = True
					i += 1
					continue
				if t.text == ";":
					self.end_statement(top)
					i += 1
					continue
			top.stmt.append(t)
			i += 1
		return self

	@staticmethod
	def reset(frame):
		frame.stmt = []
		frame.skip_stmt = False
		frame.marker = None

	@staticmethod
	def is_function_body(stmt):
		texts = [t.text for t in stmt]
		if "(" not in texts:
			return not texts  # a bare block; otherwise a brace initializer
		# Constructor member-initializer list: Foo() : m_a{1}, m_b{2} {
		if ")" in texts and ":" in texts[texts.index(")"):] and (stmt[-1].kind == "ident" or texts[-1] == ">"):
			return False
		return True

	def class_head(self, i):
		"""(index of '{', name) if the class/struct keyword at i starts a definition."""
		toks = self.toks
		j = i + 1
		name = None
		if j < len(toks) and toks[j].kind == "ident" and toks[j].text not in ("abstract", "final", "sealed"):
			name = toks[j].text
			j += 1
		while self.text(j) in ("abstract", "final", "sealed"):
			j += 1
		if self.text(j) == ":":
			while j < len(toks) and toks[j].text not in ("{", ";", "(", ")", "="):
				j += 1
		if self.text(j) == "{":
			return j, name
		return None

	def declare_component(self, i, top):
		t = self.toks[i]
		close = self.match(i + 1)
		args = self.toks[i + 2:close]
		name = args[0].text if args else ""
		parent = "".join(x.text for x in args[2:]) if len(args) > 2 else ""
		if top.kind != "class" or top.name != name:
			self.error(t.line, f"BLK_DECLARE_COMPONENT({name}) must be inside class {name}")
		else:
			top.component = Component(name, parent, top.qualname, self.path, t.line)
			self.components.append(top.component)
		self.reset(top)
		j = close + 1
		if self.text(j) == ";":
			j += 1
		return j

	def property_marker(self, i, top):
		t = self.toks[i]
		j = i + 1
		if self.text(j) != "(":
			self.error(t.line, "BLK_PROPERTY needs parentheses, even with no specifiers: BLK_PROPERTY()")
			specs = {}
		else:
			close = self.match(j)
			specs = parse_specifiers(self.toks[j + 1:close], PROPERTY_SPECIFIERS, t, self.error)
			j = close + 1
		if top.kind != "class":
			self.error(t.line, "BLK_PROPERTY must be inside a class")
		else:
			top.marker = (specs, t)
		return j

	def enum_definition(self, i, top):
		"""Records an enum definition starting at i; returns the index past it, or None."""
		toks = self.toks
		j = i + 1
		if self.text(j) in ("class", "struct"):
			j += 1
		name = None
		if j < len(toks) and toks[j].kind == "ident":
			name = toks[j].text
			j += 1
		if self.text(j) == ":":
			while j < len(toks) and toks[j].text not in ("{", ";"):
				j += 1
		if self.text(j) != "{":
			return None  # a forward declaration or an elaborated type specifier
		close = self.match(j)
		if name:
			enumerators, problem = self.enumerators(j + 1, close)
			self.enums.append(Enum(name, scoped(top.qualname, name), self.path, toks[i].line, enumerators, problem))
		if top.marker:
			self.error(top.marker[1].line, "BLK_PROPERTY must be followed by a data member declaration")
		top.marker = None
		top.skip_stmt = True
		return close + 1

	def enumerators(self, start, end):
		chunks, cur, depth = [], [], 0
		problem = None
		for t in self.toks[start:end]:
			if t.kind == "pp":
				problem = "preprocessor directives inside a reflected enum aren't supported"
				continue
			if t.kind == "punct" and t.text in ("(", "[", "{"):
				depth += 1
			elif t.kind == "punct" and t.text in (")", "]", "}"):
				depth -= 1
			if t.kind == "punct" and t.text == "," and depth == 0:
				chunks.append(cur)
				cur = []
			else:
				cur.append(t)
		chunks.append(cur)

		result = []
		for chunk in chunks:
			if not chunk:
				continue
			ident = chunk[0]
			if ident.kind != "ident":
				problem = problem or f"can't read enumerator at '{ident.text}'"
				continue
			saved_name, skip = None, False
			k = 1
			while k < len(chunk):
				x = chunk[k]
				if x.text == "BLK_ENUM":
					if k + 1 >= len(chunk) or chunk[k + 1].text != "(":
						problem = problem or "BLK_ENUM needs parentheses: BLK_ENUM(Skip)"
						break
					close, depth = None, 0
					for idx in range(k + 1, len(chunk)):
						if chunk[idx].kind != "punct":
							continue
						depth += (chunk[idx].text == "(") - (chunk[idx].text == ")")
						if depth == 0:
							close = idx
							break
					if close is None:
						problem = problem or f"unclosed BLK_ENUM( after {ident.text}"
						break
					messages = []
					specs = parse_specifiers(chunk[k + 2:close], ENUM_SPECIFIERS, x, lambda line, msg: messages.append(msg))
					if messages:
						problem = problem or messages[0]
						break
					saved_name = specs.get("SerializedAs", saved_name)
					skip = skip or bool(specs.get("Skip"))
					k = close + 1
					continue
				if x.text == "=":
					problem = problem or f"{ident.text} has an explicit value, but saved enums are matched by position"
				else:
					problem = problem or f"unexpected '{x.text}' after enumerator {ident.text}"
				break
			result.append(Enumerator(ident.text, saved_name, skip, ident.line, ident.pos + len(ident.text)))
		return result, problem

	def close_class(self, frame):
		if frame.marker:
			self.error(frame.marker[1].line, "BLK_PROPERTY must be followed by a data member declaration")
		if not frame.props:
			return
		if frame.component is None:
			for p in frame.props:
				self.error(p.line, f"BLK_PROPERTY in {frame.name}, which has no BLK_DECLARE_COMPONENT")
		else:
			frame.component.props.extend(frame.props)

	def end_statement(self, top):
		if top.skip_stmt:
			self.reset(top)
			return
		stmt, marker = top.stmt, top.marker
		if top.kind == "class" and stmt:
			decl, problem = analyze_member(stmt)
			if decl:
				name, type_tokens = decl
				self.members.append(Member(top.qualname, name, type_tokens, problem, self.path, stmt[0].line, stmt[0].pos))
			if marker:
				if decl is None or problem:
					self.error(marker[1].line, problem or "BLK_PROPERTY must be followed by a data member declaration")
				else:
					top.props.append(Property(decl[0], decl[1], marker[0].get("SerializedAs"), marker[1].line, marker[0]))
		elif marker:
			self.error(marker[1].line, "BLK_PROPERTY must be followed by a data member declaration")
		self.reset(top)


NOT_DATA = {"typedef", "using", "friend", "virtual", "explicit", "template", "static_assert", "operator"}


def analyze_member(stmt):
	"""((name, type tokens), problem) for a data member declaration, else (None, None)."""
	k = 0
	static = False
	while k < len(stmt) and stmt[k].text in ("static", "mutable", "inline", "constexpr", "thread_local"):
		static |= stmt[k].text == "static"
		k += 1
	if k >= len(stmt) or stmt[k].text in NOT_DATA or any(t.text == "operator" for t in stmt):
		return None, None

	problem = "static members can't be reflected" if static else None
	angle = paren = 0
	end = len(stmt)
	for idx in range(k, len(stmt)):
		t = stmt[idx]
		if t.kind != "punct":
			continue
		x = t.text
		if x == "<":
			angle += 1
		elif x == ">" and angle:
			angle -= 1
		elif x in ("(", "["):
			if angle == 0 and paren == 0:
				if x == "(":
					return None, None  # a function
				problem = problem or "C arrays can't be reflected; use std::vector"
				end = idx
				break
			paren += 1
		elif x in (")", "]"):
			paren -= 1
		elif angle == 0 and paren == 0:
			if x in ("=", "{"):
				end = idx
				break
			if x == ",":
				problem = problem or "declare one member per BLK_PROPERTY"
			elif x == ":":
				problem = problem or "bit-fields can't be reflected"
				end = idx
				break

	decl = stmt[k:end]
	if len(decl) < 2 or decl[-1].kind != "ident":
		return None, None
	return (decl[-1].text, decl[:-1]), problem


# ---------------------------------------------------------------------------
# Generation

@dataclass
class Field:
	saved_name: str
	tag: str
	member: str
	is_array: bool
	struct_name: str
	cpp_type: str
	line: int
	min_val: float | None = None
	max_val: float | None = None


def type_text(tokens):
	out, prev_word = "", False
	for t in tokens:
		word = t.kind in ("ident", "number")
		if out and word and prev_word:
			out += " "
		out += t.text
		prev_word = word
	return out


def qualify_std(text):
	return re.sub(r"(?<![\w:])vector<", "std::vector<", text)


def normalize(tokens):
	kept = [t for t in tokens if t.text not in ("const", "volatile", "class", "struct", "enum", "typename")]
	text = qualify_std(type_text(kept))
	return "std::string" if text == "string" else text


def derive_name(member):
	"""m_min_spawn_rate -> MinSpawnRate, m_pWaveFile -> WaveFile, m_start_3d_offset -> Start3DOffset."""
	s = member[2:] if member.startswith("m_") else member
	if len(s) > 1 and s[0] in "pb" and s[1].isupper():
		s = s[1:]
	name = "".join(part[:1].upper() + part[1:] for part in s.split("_") if part)
	return re.sub(r"(?<=\d)[a-z]", lambda m: m.group().upper(), name)


def shared_prefix(idents):
	"""The prefix every enumerator shares, up to its last underscore: CullMode_ for CullMode_None."""
	if not idents:
		return ""
	common = os.path.commonprefix(idents)
	return common[:common.rfind("_") + 1]


def parse_tree(roots, diag, exclude):
	parsers = []
	for root in roots:
		for dirpath, dirnames, filenames in os.walk(os.path.join(REPO, root)):
			dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
			for f in sorted(filenames):
				if not f.endswith(".h"):
					continue
				path = os.path.normpath(os.path.join(dirpath, f))
				if path in exclude:
					continue
				with open(path, encoding="utf-8", errors="surrogateescape", newline="") as fh:
					text = fh.read()
				if "enum" not in text and "BLK_" not in text:
					continue
				parsers.append(HeaderParser(path, text, diag).parse())
	return parsers


class Resolver:
	def __init__(self, parsers):
		self.components = {}
		self.enums = {}
		for p in parsers:
			for c in p.components:
				self.components.setdefault(c.name, c)
			for e in p.enums:
				self.enums.setdefault(e.qualname, e)

	def find_enum(self, name, comp):
		if "::" in name:
			return self.enums.get(name)
		c = comp
		while c is not None:
			e = self.enums.get(f"{c.qualname}::{name}")
			if e:
				return e
			c = self.components.get(c.parent)
		return self.enums.get(name)

	def field(self, prop, comp, diag, used_enums):
		norm = normalize(prop.type_tokens)
		m = re.fullmatch(r"std::vector<(.+)>", norm)
		elem = m.group(1) if m else norm
		is_array = m is not None
		cpp_type = qualify_std(type_text(prop.type_tokens))

		enum = None if elem in SCALAR_TAGS else self.find_enum(elem, comp)
		if elem in SCALAR_TAGS:
			tag, struct_name = SCALAR_TAGS[elem], ""
			if is_array:
				struct_name = PRIMITIVE_ARRAY_KEYS.get(elem)
				if struct_name is None:
					diag.error(comp.path, prop.line, f"std::vector<{elem}> has no vector operations registered in NameToTypeInfoMap()")
					return None
		elif enum is not None:
			if is_array:
				diag.error(comp.path, prop.line, "arrays of enums can't be reflected")
				return None
			tag, struct_name = "ENUM", enum.name
			used_enums.setdefault(enum.qualname, enum)
			if "::" not in elem and enum.qualname != enum.name:
				cpp_type = re.sub(rf"(?<![\w:]){re.escape(elem)}\b", enum.qualname, cpp_type)
		elif elem in self.components:
			tag, struct_name = "STRUCT", elem
		else:
			diag.error(comp.path, prop.line, f"no BLK_TYPEINFO tag for type '{norm}'; add it to SCALAR_TAGS in {os.path.relpath(__file__, REPO)}")
			return None

		min_val, max_val = prop.specs.get("MinVal"), prop.specs.get("MaxVal")
		if min_val is not None or max_val is not None:
			if is_array or tag not in ("FLOAT", "INT"):
				diag.error(comp.path, prop.line, f"MinVal/MaxVal only apply to a single FLOAT or INT property, and {prop.member} is '{norm}'")
				min_val = max_val = None
			elif min_val is not None and max_val is not None and min_val > max_val:
				diag.error(comp.path, prop.line, f"MinVal {min_val:g} is greater than MaxVal {max_val:g}")
				min_val = max_val = None

		derived = derive_name(prop.member)
		if prop.saved_name == derived:
			diag.warning(comp.path, prop.line, f'BLK_PROPERTY derives "{derived}" from {prop.member} already; use plain BLK_PROPERTY')
		saved_name = prop.saved_name or derived
		return Field(saved_name, tag, prop.member, is_array, struct_name, cpp_type, prop.line, min_val, max_val)


def enum_values(enum, diag):
	if enum.problem:
		diag.error(enum.path, enum.line, f"enum {enum.name}: {enum.problem}")
	first_skip = next((k for k, x in enumerate(enum.enumerators) if x.skip), len(enum.enumerators))
	if any(not x.skip for x in enum.enumerators[first_skip:]):
		diag.error(enum.path, enum.line, f"enum {enum.name}: BLK_ENUM_SKIP only works on trailing enumerators - saved enums are matched by position")
	kept = enum.enumerators[:first_skip]
	prefix = shared_prefix([x.ident for x in kept])
	values = []
	for x in kept:
		derived = x.ident[len(prefix):]
		if x.saved_name == derived:
			diag.warning(enum.path, x.line, f'{x.ident} is saved as "{derived}" already; drop the SerializedAs')
		values.append((x.ident, x.saved_name if x.saved_name is not None else derived))
	return values


def generate(project, diag):
	cfg = PROJECTS[project]
	outputs = {os.path.normpath(os.path.join(REPO, p[k])) for p in PROJECTS.values() for k in ("tables", "instances")}
	scan = parse_tree(cfg["scan"], diag, outputs)
	context = parse_tree(cfg["context"], Diagnostics(), outputs)  # the context project reports its own problems
	resolver = Resolver(scan + context)

	components = [c for p in scan for c in p.components]
	seen_components = {}
	for c in components:
		if c.name in seen_components:
			diag.error(c.path, c.line, f"{c.name} is declared twice (also {seen_components[c.name]})")
		seen_components[c.name] = f"{c.path}({c.line})"

	# Enums the context project already reflects.
	context_enums = {}
	for p in context:
		for c in p.components:
			for prop in c.props:
				resolver.field(prop, c, Diagnostics(), context_enums)

	used_enums, classes = {}, []
	for c in components:
		if not c.props:
			diag.error(c.path, c.line, f"{c.name} has no BLK_PROPERTY members; TypeInfoHierarchyIterator needs at least one per class")
		fields, saved = [], {}
		for prop in c.props:
			f = resolver.field(prop, c, diag, used_enums)
			if f is None:
				continue
			if f.saved_name in saved:
				diag.error(c.path, prop.line, f'{c.name} already saves a property as "{f.saved_name}" (line {saved[f.saved_name]})')
			saved[f.saved_name] = prop.line
			fields.append(f)
		classes.append((c, fields))

	# A key has to be unique across the whole hierarchy, not just one class: the loader
	# takes the first match walking the ancestor chain, so a derived class repeating an
	# inherited key silently reads into the ancestor's member.
	keys_by_class = {c.name: {f.saved_name: f for f in fields} for c, fields in classes}
	for c, fields in classes:
		ancestor = resolver.components.get(c.parent)
		while ancestor is not None:
			for name, f in keys_by_class.get(ancestor.name, {}).items():
				mine = keys_by_class[c.name].get(name)
				if mine is not None:
					diag.error(c.path, mine.line, f'{c.name}::{mine.member} is saved as "{name}", which {ancestor.name}::{f.member} already uses; the loader would read into {ancestor.name}\'s member')
			ancestor = resolver.components.get(ancestor.parent)

	scan_enums = {id(e) for p in scan for e in p.enums}
	enums, enum_names = [], {}
	for qualname, e in used_enums.items():
		if id(e) not in scan_enums:
			if qualname not in context_enums:
				diag.error(e.path, e.line, f"enum {e.name} is used by a {project} property but defined in, and not reflected by, another project")
			continue
		if e.name in enum_names:
			diag.error(e.path, e.line, f"two reflected enums are named {e.name} (also {enum_names[e.name]})")
		enum_names[e.name] = f"{e.path}({e.line})"
		enums.append(e)
	enums.sort(key=lambda e: (e.path, e.line))
	enum_blocks = [(e, enum_values(e, diag)) for e in enums]

	return emit_tables(enum_blocks, classes), emit_instances(enum_blocks, classes)


def emit_tables(enum_blocks, classes):
	out = [HEADER, "// clang-format off"]
	for e, values in enum_blocks:
		out.append("GenerateEnum(")
		out.append(f'\t{e.name}, "{e.name}",')
		out += [f'\tAddEnumField({ident}, "{name}")' for ident, name in values]
		out += [")", ""]
	for c, fields in classes:
		out.append("GenerateClass(")
		out.append(f"\t{c.name},")
		for f in fields:
			is_array = "true" if f.is_array else "false"
			out.append(f'\tAddField("{f.saved_name}", BLK_TYPEINFO_{f.tag}, {c.name}, {f.member}, {is_array}, "{f.struct_name}", {f.cpp_type})')
			if f.min_val is not None:
				out.append(f'\tSetFieldMin("{f.saved_name}", {f.min_val:g})')
			if f.max_val is not None:
				out.append(f'\tSetFieldMax("{f.saved_name}", {f.max_val:g})')
		out += [")", ""]
	return "\n".join(out)


def emit_instances(enum_blocks, classes):
	out = [HEADER, "// clang-format off"]
	out += [f"{e.name}_Enum {e.name}_EnumClass;" for e, _ in enum_blocks]
	out += [f"BLK_DEFINE_CLASS({c.name})" for c, _ in classes]
	return "\n".join(out) + "\n"


def main():
	ap = argparse.ArgumentParser(description="Generate reflection tables from BLK_PROPERTY markers.")
	ap.add_argument("projects", nargs="*", metavar="project", help=f"{' or '.join(PROJECTS)} (default: all)")
	ap.add_argument("--check", action="store_true", help="exit 1 if an output is stale instead of writing it")
	args = ap.parse_args()
	for p in args.projects:
		if p not in PROJECTS:
			ap.error(f"unknown project {p!r}")

	diag = Diagnostics()
	writes = []
	for p in args.projects or list(PROJECTS):
		tables, instances = generate(p, diag)
		writes += [(PROJECTS[p]["tables"], tables), (PROJECTS[p]["instances"], instances)]

	for w in diag.warnings:
		print(w)
	if diag.errors:
		for e in diag.errors:
			print(e)
		return 1

	stale = False
	for rel, content in writes:
		path = os.path.join(REPO, rel)
		new = content.replace("\n", "\r\n")
		try:
			with open(path, encoding="utf-8", newline="") as fh:
				old = fh.read()
		except FileNotFoundError:
			old = None
		if old == new:
			continue
		if args.check:
			print(f"{os.path.normpath(path)}(1): error TYPEINFO: out of date; run python {os.path.relpath(__file__, REPO)}")
			stale = True
			continue
		with open(path, "w", encoding="utf-8", newline="") as fh:
			fh.write(new)
		print(f"type_info: regenerated {rel}")
	return 1 if stale else 0


if __name__ == "__main__":
	sys.exit(main())
