// Generated by tools/type_info/generate_type_info.py from the BLK_PROPERTY markers
// in the component headers. Don't edit it - the build regenerates it.

// clang-format off
ECameraMoveMode_Enum ECameraMoveMode_EnumClass;
BLK_DEFINE_CLASS(CannonCameraShakeComponent)
BLK_DEFINE_CLASS(CannonCameraComponent)
BLK_DEFINE_CLASS(CannonLevelComponent)
BLK_DEFINE_CLASS(CannonFogComponent)
