// Generated by tools/type_info/generate_type_info.py from the BLK_PROPERTY markers
// in the component headers. Don't edit it - the build regenerates it.
//
// Every name below is on-disk format. Property keys derive from member names and enum
// values from enumerator names, so renaming either renames the key in every level file:
// migrate the levels in the same change, or pin the old name with SerializedAs. The
// loader skips a key it doesn't recognise and resets an unmatched enum value to the
// first enumerator, in both cases without failing.

// clang-format off
GenerateEnum(
	ECameraMoveMode, "ECameraMoveMode",
	AddEnumField(MoveMode_None, "None")
	AddEnumField(MoveMode_Follow, "Follow")
)

GenerateClass(
	CannonCameraShakeComponent,
	AddField("Duration", BLK_TYPEINFO_FLOAT, CannonCameraShakeComponent, m_Duration, false, "", float)
	AddField("AmplitudeX", BLK_TYPEINFO_FLOAT, CannonCameraShakeComponent, m_AmplitudeX, false, "", float)
	AddField("AmplitudeY", BLK_TYPEINFO_FLOAT, CannonCameraShakeComponent, m_AmplitudeY, false, "", float)
	AddField("FrequencyX", BLK_TYPEINFO_FLOAT, CannonCameraShakeComponent, m_FrequencyX, false, "", float)
	AddField("FrequencyY", BLK_TYPEINFO_FLOAT, CannonCameraShakeComponent, m_FrequencyY, false, "", float)
	AddField("ActivationDelaySeconds", BLK_TYPEINFO_FLOAT, CannonCameraShakeComponent, m_ActivationDelaySeconds, false, "", float)
	AddField("ActivateOnEnable", BLK_TYPEINFO_BOOL, CannonCameraShakeComponent, m_bActivateOnEnable, false, "", bool)
)

GenerateClass(
	CannonCameraComponent,
	AddField("NearPlane", BLK_TYPEINFO_FLOAT, CannonCameraComponent, m_NearPlane, false, "", float)
	AddField("FarPlane", BLK_TYPEINFO_FLOAT, CannonCameraComponent, m_FarPlane, false, "", float)
	AddField("PositionOffset", BLK_TYPEINFO_VECTOR, CannonCameraComponent, m_positionOffset, false, "", Vec3)
	AddField("LookAtOffset", BLK_TYPEINFO_VECTOR, CannonCameraComponent, m_LookAtOffset, false, "", Vec3)
	AddField("MoveMode", BLK_TYPEINFO_ENUM, CannonCameraComponent, m_MoveMode, false, "ECameraMoveMode", ECameraMoveMode)
)

GenerateClass(
	CannonLevelComponent,
	AddField("Dummy2", BLK_TYPEINFO_INT, CannonLevelComponent, m_Dummy2, false, "", int)
)

GenerateClass(
	CannonFogComponent,
	AddField("Shader", BLK_TYPEINFO_SHADER, CannonFogComponent, m_shader, false, "", Shader*)
	AddField("FogStartDist", BLK_TYPEINFO_FLOAT, CannonFogComponent, m_FogStartDist, false, "", float)
	AddField("FogEndDist", BLK_TYPEINFO_FLOAT, CannonFogComponent, m_FogEndDist, false, "", float)
	AddField("FogClamp", BLK_TYPEINFO_FLOAT, CannonFogComponent, m_FogClamp, false, "", float)
	AddField("FogColor", BLK_TYPEINFO_VECTOR4, CannonFogComponent, m_FogColor, false, "", Color)
)
