// Generated by tools/type_info/generate_type_info.py from the BLK_PROPERTY markers
// in the component headers. Don't edit it - the build regenerates it.
//
// Every name below is on-disk format. Property keys derive from member names and enum
// values from enumerator names, so renaming either renames the key in every level file:
// migrate the levels in the same change, or pin the old name with SerializedAs. The
// loader skips a key it doesn't recognise and resets an unmatched enum value to the
// first enumerator, in both cases without failing.

// clang-format off
ECameraMoveMode_Enum ECameraMoveMode_EnumClass;
BLK_DEFINE_CLASS(CannonCameraShakeComponent)
BLK_DEFINE_CLASS(CannonCameraComponent)
BLK_DEFINE_CLASS(CannonLevelComponent)
BLK_DEFINE_CLASS(CannonFogComponent)
